# Generated by Django 3.0.3 on 2020-08-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_item_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='two-products'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='catagory',
            field=models.CharField(choices=[('FA', 'Fashion'), ('MW', 'Man Watches'), ('WW', 'Woman Watches'), ('FJ', 'Fine Jewelry'), ('EW', 'Engagement Wedding'), ('MJ', 'Man Jewelry'), ('VA', 'Vintage Antique'), ('LD', 'Loose Dimonds'), ('LD', 'Loose Beads')], max_length=2),
        ),
    ]
